steps:

  # UNCOMMENT if requirements has changed
  - id: Image Build
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_IMAGE_NAME}:${_IMAGE_TAG}", "."]

  - id: Image Push
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_IMAGE_NAME}:${_IMAGE_TAG}"]  

  - id: Run Webpack Build
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args: 
    - -c
    - |-
      docker run --volume /workspace:/home/node/app ${_IMAGE_NAME}:${_IMAGE_TAG} sh -c "yarn install && export NODE_ENV=production && node node_modules/.bin/webpack"

  - id: Uploading artifacts to GCP Cloud Storage
    name: "gcr.io/cloud-builders/gsutil"
    args: ["cp", "-r", "./home", "gs://monitor-financeiro/"]

substitutions:
  _IMAGE_NAME: us.gcr.io/${PROJECT_ID}/${REPO_NAME}
  _IMAGE_TAG: v1
