version: '3'
services:
    app:
        build:
            context: .
        volumes:
            - .:/app
        command: gunicorn --bind 0.0.0.0:8080 routing:app
        ports:
        - 8080:8080