version: '2'
services:
    
    postgres:
       image: postgres:10.6
       ports:
         - "5432:5432"
       restart: always
       volumes:
           - $PWD/vendor/nasajon/bancosweb/dump:/docker-entrypoint-initdb.d/
       environment:
           - "POSTGRES_DB=integratto2"
           - "POSTGRES_USER=bancosweb"
           - "POSTGRES_PASSWORD=mysecretpassword"   

    app:
      image: nasajon/php:7.1-fpm-symfony-dev
      restart: always
      ports:
        - "80:80"
      expose:
        - "9000"
      volumes:
        - $PWD:/var/www/html
        - ./default.conf:/etc/nginx/conf.d/default.conf
      env_file:
        - ./common.env
        
    transformer:
       image: nasajon/php-node    
       volumes:
             - ./:/var/www/html
       working_dir: /var/www/html
       entrypoint: php vendor/nasajon/mdatransformer/bin/convert nasajon:mda:builder --nocache -vvv --cleardir
    
    rabbitmq:
      image: rabbitmq:3-management
      expose:
        - "6379"
      ports:
        - "15672:15672"
      restart: always
      environment:
        - "RABBITMQ_DEFAULT_VHOST=atendimento"

    memcached:
      image: memcached
      restart: always
      hostname: memcache
      mem_limit: 268435456
      expose:
        - "11211"

    # regras:
    #   image: nasajon/php:7.1-fpm-symfony-dev
    #   restart: always
    #   volumes:
    #     - $PWD:/var/www/html
    #     - ./default.conf:/etc/nginx/conf.d/default.conf
    #   env_file:
    #     - ./common.env
    #   command:
    #     - app/console
    #     - rabbitmq:consume
    #     - chamados_regras
    #     - --env=prod
    #   depends_on:
    #     - rabbitmq

    # chamadosla:
    #   image: nasajon/php:7.1-fpm-symfony-dev
    #   restart: always
    #   volumes:
    #     - $PWD:/var/www/html
    #     - ./default.conf:/etc/nginx/conf.d/default.conf
    #   env_file:
    #     - ./common.env
    #   command:
    #     - app/console
    #     - rabbitmq:consume
    #     - chamados_slas
    #     - --env=prod
    #   depends_on:
    #     - rabbitmq

    # processasla:
    #   image: nasajon/php:7.1-fpm-symfony-dev
    #   restart: always
    #   volumes:
    #     - $PWD:/var/www/html
    #     - ./default.conf:/etc/nginx/conf.d/default.conf
    #   env_file:
    #     - ./common.env
    #   command:
    #     - app/console
    #     - rabbitmq:consume
    #     - slas
    #     - --env=prod
    #   depends_on:
    #     - rabbitmq

    # violacaosla:
    #   image: nasajon/php:7.1-fpm-symfony-dev
    #   restart: always
    #   volumes:
    #     - $PWD:/var/www/html
    #     - ./default.conf:/etc/nginx/conf.d/default.conf
    #   env_file:
    #     - ./common.env
    #   command:
    #     - app/console
    #     - rabbitmq:consume
    #     - chamados_slas_violacao
    #     - --env=prod
    #   depends_on:
    #     - rabbitmq

    # registraviolacaosla:
    #   image: nasajon/php:7.1-fpm-symfony-dev
    #   restart: always
    #   volumes:
    #     - $PWD:/var/www/html
    #     - ./default.conf:/etc/nginx/conf.d/default.conf
    #   env_file:
    #     - ./common.env
    #   command:
    #     - app/console
    #     - rabbitmq:consume
    #     - chamados_sla_registra_violacao_sla
    #     - --env=prod
    #   depends_on:
    #     - rabbitmq
    
    # somaresumos:
    #   image: nasajon/php:7.1-fpm-symfony-dev
    #   volumes:
    #     - $PWD:/var/www/html
    #     - ./default.conf:/etc/nginx/conf.d/default.conf
    #   env_file:
    #     - ./common.env
    #   command:
    #     - app/console
    #     - app:soma-resumos
    #   depends_on:
    #     - rabbitmq

    # enfileirachamadosslasviolados:
    #   image: nasajon/php:7.1-fpm-symfony-dev
    #   volumes:
    #     - $PWD:/var/www/html
    #     - ./default.conf:/etc/nginx/conf.d/default.conf
    #   env_file:
    #     - ./common.env
    #   command:
    #     - app/console
    #     - app:enfileira-chamados-slas-violados
    #   depends_on:
    #     - rabbitmq