version: '2'

services:
    
    webpack:
        image: "nasajon/yarn"
        working_dir: /home/node/app
        environment:
        - NODE_ENV=development        
        volumes:
        - ./:/home/node/app
        ports:
        - "9000:9000"
        command: "node node_modules/.bin/webpack-dev-server"
        
    gerarprod:
        image: "nasajon/yarn"
        working_dir: /home/node/app
        environment:
        - NODE_ENV=production        
        volumes:
        - ./:/home/node/app
        command: "node node_modules/.bin/webpack-dev-server"
