swagger: "2.0"
info:
  description: "Routing API. All distances should be in minutes."
  version: "1.0.0"
  title: "Routing API"
  termsOfService: ""
  contact:
    email: "nilton.gduarte@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:5000"
basePath: "/v1"
tags:
- name: "Routing API"

schemes:
- "http"

