imports:
    - { resource: config.yml }

framework:
    session:
        handler_id: session.handler.memcached
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
assetic:
    use_controller: false
    filters:
        cssrewrite: ~
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        filter_info:
            type: service
            id: cloudwatch_handler
            level:  warning
        console:
            type:  console
            level:  warning
            process_psr_3_messages: false
            channels: ['!doctrine', '!console', '!event']

doctrine_cache:
    providers:
        my_memcached:
            memcached:
                servers:
                        "%env(memcached_host)%" : "%env(memcached_port)%"
            aliases:
                - nasajon_login_bundle_cache
         
sentry:
    dsn: "https://f5b081b19f854e78b3b6300acb478ef3:f1688abedd9248b399d92b88b678ede3@sentry.nasajon.com.br/4"
    options:
        environment: %env(sentry_env)%
