imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler:
        only_exceptions: false        

web_profiler:
    toolbar: true
    intercept_redirects: false

assetic:
    use_controller: true
    filters:
        uglifyjs2: ~
        uglifycss: ~

monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event"]
        console:
            type:   console
            bubble: false
            level:  info
            channels: ['!doctrine', '!console', '!event']
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

#swiftmailer:
#    delivery_address: me@example.com

doctrine_migrations:
    dir_name: "%kernel.project_dir%/vendor/nasajon/bancosweb/database"
    namespace: DoctrineMigrations
    table_name: migration_versions
    name: Application Migrations
    organize_migrations: false