version: '2'

services:
    app:
        image: nasajon/php:7.1-fpm-symfony-dev
        restart: always
        ports:
            - "80:80"
            - "3000:3000"
            - "3001:3001"            
        volumes:
            - $PWD:/var/www/html
            - $PWD/nginx:/etc/nginx/conf.d
        env_file:
            - common.env
        environment: 
            - "NODE_ENV=development"

    postgres:
       image: postgres:11.5
       ports:
         - "5432:5432"
       restart: always
       volumes:
           - $PWD/vendor/nasajon/bancosweb/dump:/docker-entrypoint-initdb.d/
           - $PWD/scripts:/scripts
       environment:
           - "POSTGRES_DB=integratto2"
           - "POSTGRES_USER=postgres"
           - "POSTGRES_PASSWORD=postgres" 
      
    transformer:
        image: nasajon/php-node
        volumes:
              - $PWD:/var/www/html
        working_dir: /var/www/html
        environment: 
            - "NODE_ENV=development"
        entrypoint: php vendor/nasajon/mdatransformer/bin/transformer nasajon:mda:builder --nocache -vvv --cleardir

    memcache:
      image: memcached
      restart: always
      hostname: memcache
      mem_limit: "268435456"
      expose:
        - "11211"
