node('aws-codebuild') {

   stage('Fetch') {
        timeout(time: 60, unit: 'SECONDS') {
            checkout scm
        }
    }


	
     if (env.BRANCH_NAME == 'master') {
	     stage('Deploy QA'){
             sh "ansible-playbook ${PLAYBOOK} -e 'build_path=${WORKSPACE} env=qa'"
         }
     }
	
     if (env.BRANCH_NAME == 'production') {
	     stage('Deploy PROD'){
             sh "ansible-playbook ${PLAYBOOK} -e 'build_path=${WORKSPACE} env=prod'"
         }
     }
}
