ekreative_health_check:
    resource: "@EkreativeHealthCheckBundle/Controller/"
    type:     annotation
    prefix:   /

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix: /fosrouting

options:
    resource: "routing/options.yml"
    type: rest
    prefix: /api/{tenant}
    options:
        expose: true

api:
    resource: "routing/app.yml"
    type: rest
    prefix: /api/{tenant}
    type: rest
    options:
        expose: true

options:
    resource: "routing/options.yml"
    type: rest
    prefix: /api
    options:
        expose: true

options_uploader_documentos:
    controller: "Nasajon\\AppBundle\\Controller\\PingController::optionsNoBarAction"
    path:     "/_uploader/documentos/upload"
    methods:  ["OPTIONS"]

options_profile:
    controller: "Nasajon\\AppBundle\\Controller\\PingController::optionsNoBarAction"
    path:     "/profile"
    methods:  ["OPTIONS"]

application:
    resource: "@NasajonLoginBundle/Controller/ProfileController.php"
    type: annotation
    prefix: /
    options:
        expose: true

login_bundle_keycloak:
    resource: "@NasajonLoginBundle/Controller/KeycloakController.php"
    type:     annotation
    prefix: /
    options:
        expose: true

oneup_uploader:
  resource: .
  type: uploader
  options:
      expose: true
  
index:
    type: rest
    resource: "Nasajon\\AppBundle\\Controller\\IndexController"
    defaults:
        html5mode: 'home'
    requirements:
        html5mode: .+
    
index_trailing_slash:
    path: /{tenant}/
    defaults:
        _controller:  FrameworkBundle:Template:template
        template: '@NasajonMDABundle/Resources/js/index.html'
