import { ICliente } from '../../Ns/Clientes/cliente.interfaces';
import { IEstabelecimento } from '../../Ns/Estabelecimentos/estabelecimentos.interfaces';
import { IMunicipioPrestacao } from '../../Ns/Municipios/municipios.interfaces';
import { ISerie } from '../../Ns/Series/series.interfaces';
import { IOperacaoOrdemServico } from '../Operacoes-ordens-servicos/operacoes-ordens-servicos.interfaces';

export interface ICreatedBy {
  nome: string;
  email: string;
}

export interface IOrdemServico {
  ordemservico: string;
  serie?: any;
  datacriacao: string;
  horacriacao: string;
  origem: number;
  referenciaexterna?: any;
  logradouro?: any;
  numeroendereco?: any;
  complemento?: any;
  cep?: any;
  bairro?: any;
  uf?: any;
  cidade?: any;
  cidadeestrangeira?: any;
  situacao: number;
  situacaodescricao: string;
  operacaonome: string;
  nomeresponsavel: string;
  projeto?: any;
  observacao?: any;
  observacaointerna?: any;
  numero: number;
  tenant: number;
  created_at: string;
  created_by: ICreatedBy;
  updated_at?: any;
  updated_by?: any;
  valortotal?: any;
  grupoempresarial: string;
  responsavel?: any;
  numeronegocio?: any;
  ordemservicovisita?: any;
  datavisita?: any;
  descricaovisita?: any;
  agendado?: any;
  executado?: any;
  horaestimadainicio?: any;
  horaestimadafim?: any;
  created_at_visita?: any;
  created_by_visita?: any;
  tenant_visita?: any;
  origem_saida?: any;
  hora_saida?: any;
  data_saida?: any;
  km_saida?: any;
  hora_inicio_manutencao?: any;
  data_inicio_manutencao?: any;
  hora_termino_manutencao?: any;
  data_termino_manutencao?: any;
  parada_para_almoco?: any;
  hora_inicio_almoco?: any;
  data_inicio_almoco?: any;
  hora_termino_almoco?: any;
  data_termino_almoco?: any;
  deslocamento_extra?: any;
  hora_saida_deslocamento?: any;
  data_saida_deslocamento?: any;
  km_saida_deslocamento?: any;
  hora_chegada_deslocamento?: any;
  data_chegada_deslocamento?: any;
  km_chegada_deslocamento?: any;
  motivo_deslocamento?: any;
  hora_chegada_cliente?: any;
  data_chegada_cliente?: any;
  km_chegada_cliente?: any;
  hora_saida_cliente?: any;
  data_saida_cliente?: any;
  observacao_visita?: any;
  latitudevisita?: any;
  longitudevisita?: any;
  datavisitafim?: any;
  motivofinalizacao?: any;
  urlassinatura?: any;
  transportepublico?: any;
  situacaoagendamento: number;
  dataconfirmacaoagendamento?: any;
  nometecnicoconfirmacao: string;
  atc?: any;
  idserie: ISerie;
  estabelecimento: IEstabelecimento;
  tipologradouro?: any;
  pais?: any;
  ibge?: any;
  cliente: ICliente;
  municipioprestacao: IMunicipioPrestacao;
  enderecocliente?: any;
  ordemservicovinculada?: any;
  tipoordemservico?: any;
  operacaoordemservico: IOperacaoOrdemServico;
  ativo?: any;
  tipomanutencao?: any;
  atendimento?: any;
  veiculo?: any;
  contrato?: any;
  centrodecusto?: any;
  ordemservicotemplate: string;
  nome: string;
}
