<?php

namespace AppBundle\Enum;
/**
 * Enum para ser usado para converter nomes de campos em suas respectivas labels
 */
abstract class SolicitacoesLabelsEnum {

    const labels = [
        "anocompetencia" => 'Ano competência',
        "anodescontacalculo" => 'Ano desconta cálculo',
        "bairro" => 'Bairro',
        "beneficiosadescontar" => 'Benefícios à descontar',
        "beneficiosadescontardescricao" => 'Descrição de benefícios à descontar',
        "cargo" => 'Cargo',
        "celular" => 'Celular',
        "cep" => 'CEP',
        "colaborador" => 'Colaborador',
        "complemento" => 'Complemento',
        "conteudo" => 'Conteúdo',
        "cpf" => 'CPF',
        "data" => 'Data',
        "dataadmissao" => 'Data de admissão',
        "dataconcessaoaviso" => 'Data de concessão',
        "datafinal" => 'Data final',
        "datainicial" => 'Data inicial',
        "datanascimento" => 'Data de nascimento',
        "dataprojetadaaviso" => 'Data projetada',
        "datarescisao" => 'Data de rescisão',
        "datas" => 'Datas',
        "dddcel" => 'DDD',
        "dddtel" => 'DDD',
        "departamento" => 'Departamento',
        "descricao" => 'Descrição',
        "formapagamento" => 'Forma de pagamento',
        "historicoadiantamentoavulso" => "Histórico",
        "horario" => 'Horário',
        "indenizado" => 'Indenizado',
        "justificada" => 'Justificada',
        "justificativa" => 'Justificativa',
        "logradouro" => 'Logradouro',
        "mescompetencia" => 'Mes competência',
        "mesdescontacalculo" => 'Mês desconta cálculo',
        "mesdescontocalculo" => "Mês para Cálculo",
        "anodescontocalculo" => "Ano para Cálculo",
        "motivo" => 'Motivo',
        "movimentos" => 'Apontamentos',
        "municipioresidencia" => 'Município',
        "nivelcargo" => 'Nível cargo',
        "nome" => 'Nome',
        "nomedocumento" => 'Nome Documento',
        "numero" => 'Número',
        "observacao" => 'Observação',
        "observacaoconcessaoaviso" => 'Observação sobre a concessão',
        "orientacoescalculo" => 'Orientações para Cálculo',
        "paisresidencia" => 'País',
        "quantidade" => 'Quantidade',
        "salariofixo" => 'Salário Fixo',
        "solicitacoesalteracoesvtstarifas" => "Detalhamento das tarifas",
        "tarifaconcessionariavt" => 'Tarifa',
        "telefone" => 'Telefone',
        "tipo" => 'Tipo',
        "tipoconcessaoaviso" => 'Tipo de concessão',
        "tipoconteudo" => "Tipo",
        "tipocumprimentoaviso" => 'Tipo',
        "tipojustificativa" => 'Tipo de justificativa',
        "tipologradouro" => 'Tipo logradouro',
        "valor" => 'Valor',
        "email" => 'E-mail',
        "adto13nasferias" => 'Adiantamento de  13°',
        "dataaviso" => 'Data de Aviso',
        "datainiciogozo" => 'Data de Início de Gozo',
        "datafimgozo" => 'Data de Fim de Gozo',
        "datainicioperiodoaquisitivo" => 'Data de Início do Período Aquisitivo',
        "datafimperiodoaquisitivo" => 'Data de Fim do Período Aquisitivo',
        "diasvendidos" => 'Dias Vendidos',
        "diasferiascoletivas" => 'Dias de Férias',
        "temabonopecuniario" => 'Abono Pecuniário'
    ];
}